name: React Build and Deploy to Docker Hub

# Trigger the workflow when changes are pushed to the master branch.
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest version of Ubuntu.

    steps:
      -
        name: Checkout repository  # Step to check out the source code.
        uses: actions/checkout@v2

      -
        name: Login to Docker Hub  # Step to log in to Docker Hub.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Username from GitHub Secrets.
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Password (or token) from GitHub Secrets.

      -
        name: Set up Docker Buildx  # Step to set up Docker Buildx (Docker CLI plugin).
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push  # Step to build and push the Docker image.
        uses: docker/build-push-action@v4
        with:
          context: .                     # Build context (the current directory).
          file: ./Dockerfile             # Path to the Dockerfile.
          push: true                     # Push the built image to Docker Hub.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/evensteven:latest  # Tag for the Docker image.

